Repository MicrosoftDocs/powerapps-docs, pull requests merged in 2018-11, with the labels that each got.

#87 typo: knowlege -> knowledge
  powerapps-docs/maker/model-driven-apps/translate-localizable-text.md
Labels: 01model-driven, 02doc bug, assigned-to-contributors

#95 typo: familar -> familiar
  powerapps-docs/maker/model-driven-apps/guide-staff-through-common-tasks-processes.md
Labels: 01model-driven, 02doc bug

#89 typo: cick -> click
  powerapps-docs/maker/common-data-service/data-platform-create-entity.md
Labels: 01cds, 02doc bug, assigned-to-contributors

#108 typo: Availabilty -> Availability
  powerapps-docs/developer/common-data-service/register-plug-in.md
Labels: 01cds, 02doc bug

#107 typo: recieve -> receive
  powerapps-docs/developer/common-data-service/event-framework.md
Labels: 01cds, 02doc bug

#111 typo: capabilties -> capabilities
  powerapps-docs/developer/model-driven-apps/script-jscript-web-resources.md
Labels: 01model-driven, 02doc bug

#106 typo: begining -> beginning
  powerapps-docs/developer/common-data-service/webapi/samples/functions-actions-client-side-javascript.md
Labels: 01cds, 02doc bug

#105 typo: visbility -> visibility
  powerapps-docs/developer/common-data-service/customization-solutions-file-schema.md
Labels: 01cds, 02doc bug

#122 typo: accross -> across
  powerapps-docs/developer/model-driven-apps/use-iframe-and-web-resource-controls-on-a-form.md
Labels: 01dev

#116 Hide trash icon when change form is in New mode
  powerapps-docs/maker/canvas-apps/get-started-create-from-blank.md
Labels: 01canvas, 02enhancement
