Repository MicrosoftDocs/powerapps-docs, pull requests merged in 2020-09, with the labels that each got.

#1711 Fixing typo to processInstanceId
  powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/setActiveProcessInstance.md
Labels: assigned-to-contributors

#1697 Update Time Zone Entities documentation
  powerapps-docs/developer/common-data-service/time-zone-entities.md
Labels: do-not-merge, in-progress

#1712 Fixing typo to processId
  powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/activeprocess/setActiveProcess.md
Labels: assigned-to-contributors

#1663 Add reference to async Merge requests
  powerapps-docs/developer/common-data-service/org-service/use-executeAsync.md
Labels: assigned-to-author, in-progress, waiting-on-internal-feedback

#1717 Typo "Azure storage explorer"→"Azure Storage Explorer"
  powerapps-docs/maker/portals/admin/view-portal-error-log.md
Labels: assigned-to-contributors

#1729 Add stageGate value option
  powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/navigation/moveNext.md
Labels: assigned-to-contributors

#1730 Add stageGate value option
  powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/navigation/movePrevious.md
Labels: assigned-to-contributors

#1737 Typo corrected
  powerapps-docs/maker/portals/web-api-perform-operations.md
Labels: assigned-to-contributors

#1755 Update to include new tab behavior
  powerapps-docs/developer/component-framework/reference/navigation/openform.md
Labels: assigned-to-contributors

#1750 Adding note regarding several CDSs
  powerapps-docs/developer/common-data-service/walkthrough-register-app-azure-active-directory.md
Labels: assigned-to-contributors
