Repository MicrosoftDocs/powerapps-docs, pull requests merged in 2020-12, with the labels that each got.

#1974 Update expense-report-install.md
  powerapps-docs/maker/canvas-apps/expense-report-install.md
Labels: assigned-to-contributors

#1979 Added ref to FetchXML Builder
  powerapps-docs/developer/model-driven-apps/developer-tools.md
Labels: assigned-to-contributors

#1989 Update share-app.md
  powerapps-docs/maker/canvas-apps/share-app.md
Labels: assigned-to-contributors

#1998 Update getoutputs.md
  powerapps-docs/developer/component-framework/reference/control/getoutputs.md
Labels: assigned-to-contributors

#1949 Update calculated-rollup-attributes.md
  powerapps-docs/developer/common-data-service/calculated-rollup-attributes.md
Labels: assigned-to-author, waiting-on-internal-feedback

#2002 Update captureImage.md
  powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Device/captureImage.md
Labels: assigned-to-contributors

#2005 Update function-datetime-parts.md
  powerapps-docs/maker/canvas-apps/functions/function-datetime-parts.md
Labels: assigned-to-contributors

#2008 Update use-single-tenant-server-server-authentication.md
  powerapps-docs/developer/common-data-service/use-single-tenant-server-server-authentication.md
Labels: assigned-to-author, assigned-to-contributors

#2006 Fix to align with the changed UI
  powerapps-docs/teams/edit-delete-table.md
Labels: assigned-to-contributors
