Repository MicrosoftDocs/powerapps-docs, pull requests merged in 2020-10, with the labels that each got.

#1770 Update control-attachments.md
  powerapps-docs/maker/canvas-apps/controls/control-attachments.md
Labels: assigned-to-author, assigned-to-contributors, do-not-merge

#1793 Updated export-to-data-lake.md
  powerapps-docs/maker/common-data-service/export-to-data-lake.md
Labels: assigned-to-contributors

#1802 Typo "**P@ssw0rd**"→"**P\@ssw0rd**"
  powerapps-docs/maker/canvas-apps/controls/control-text-input.md
Labels: assigned-to-contributors

#1810 Type mistake in the docs: https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-footersection/getvisible
  powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-footerSection/getVisible.md
Labels: assigned-to-contributors

#1813 Update create-connection-reference.md
  powerapps-docs/maker/common-data-service/create-connection-reference.md
Labels: assigned-to-contributors

#1426 Indicate that plugins are not fired by SQL queries
  powerapps-docs/developer/common-data-service/cds-sql-query.md
Labels: assigned-to-contributors

#1819 Update clientapi-form-context.md
  powerapps-docs/developer/model-driven-apps/clientapi/clientapi-form-context.md
Labels: assigned-to-contributors

#1812 Update openForm.md
  powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md
Labels: assigned-to-author, client-api, do-not-merge, waiting-on-internal-feedback

#1814 Update why-cds-import-export.md
  powerapps-docs/maker/common-data-service/why-cds-import-export.md
Labels: assigned-to-contributors

#1849 Update function-filter-lookup.md
  powerapps-docs/maker/canvas-apps/functions/function-filter-lookup.md
Labels: assigned-to-contributors

#1863 Changing owner of SSS PM
  powerapps-docs/developer/common-data-service/configure-exchange-folder-level-tracking-rules.md
Labels: assigned-to-contributors
