Repository MicrosoftDocs/powerapps-docs, pull requests merged in 2020-08, with the labels that each got.

#1592 Clarify use of column comparison
  powerapps-docs/developer/common-data-service/org-service/use-conditionexpression-class.md
Labels: assigned-to-author

#1649 Fixed incomplete connection strings
  powerapps-docs/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect.md
Labels: assigned-to-contributors

#1656 Async support for conditional icons
  powerapps-docs/maker/common-data-service/display-custom-icons-instead.md
Labels: assigned-to-contributors

#1658 Discover Hub for Export to Data Lake
  powerapps-docs/maker/common-data-service/export-to-data-lake.md
  powerapps-docs/maker/common-data-service/media/discover-hub.png
Labels: assigned-to-contributors

#1659 Update export-to-data-lake-data-adf.md
  powerapps-docs/maker/common-data-service/export-to-data-lake-data-adf.md
Labels: assigned-to-contributors

#1660 Update export-to-data-lake-data-powerbi.md
  powerapps-docs/maker/common-data-service/export-to-data-lake-data-powerbi.md
Labels: assigned-to-contributors

#1677 Update behavior-format-date-time-attribute.md
  powerapps-docs/developer/common-data-service/behavior-format-date-time-attribute.md
Labels: assigned-to-contributors

#1668 Fix embedded canvas apps limitation
  powerapps-docs/maker/model-driven-apps/embedded-canvas-app-guidelines.md
Labels: assigned-to-contributors, waiting-on-internal-feedback

#1686 Update create-edit-quick-create-forms.md
  powerapps-docs/maker/model-driven-apps/create-edit-quick-create-forms.md
Labels: assigned-to-author, assigned-to-contributors, waiting-on-internal-feedback

#1521 Removed note specific to Azure Service Bus
  powerapps-docs/developer/common-data-service/use-webhooks.md
Labels: assigned-to-author
