Repository MicrosoftDocs/powerapps-docs, pull requests merged in 2021-07, with the labels that each got.

#2500 Replace JSON with YAML
  powerapps-docs/maker/portals/power-apps-cli.md
Labels: Portals, assigned-to-contributors

#2508 Update work-with-any-data.md
  powerapps-docs/maker/data-platform/work-with-any-data.md
Labels: assigned-to-contributors

#2512 Update type-group.md
  powerapps-docs/developer/component-framework/manifest-schema-reference/type-group.md
Labels: assigned-to-contributors

#2502 There is no setNotification in formContext.ui. The correct method is setFormNotification.
  powerapps-docs/developer/model-driven-apps/clientapi/reference/events/postsave.md
Labels: assigned-to-contributors

#2503 PowerApps CLI - arguments for auth
  powerapps-docs/developer/data-platform/powerapps-cli.md
Labels: assigned-to-contributors, waiting-on-internal-feedback

#2524 Update type-group.md with better examples of the functionality
  powerapps-docs/developer/component-framework/manifest-schema-reference/type-group.md
Labels: assigned-to-contributors

#2528 Update powerapps-cli.md
  powerapps-docs/developer/data-platform/powerapps-cli.md
Labels: assigned-to-contributors

#2544 Update workflow-extensions.md
  powerapps-docs/developer/data-platform/workflow/workflow-extensions.md
Labels: assigned-to-contributors

#2529 Update create-connection-reference.md
  powerapps-docs/maker/data-platform/create-connection-reference.md
Labels: assigned-to-contributors

#2556 Remove duplicated word
  powerapps-docs/developer/data-platform/powerapps-cli.md
Labels: assigned-to-contributors

#2560 Add: prod build version command
  powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md
Labels: assigned-to-contributors

#2562 Changed to the name of my blog
  powerapps-docs/developer/component-framework/community-resources.md
Labels: assigned-to-contributors, waiting-on-internal-feedback

#2568 Update appendix-add-license-information-to-your-solution.md
  powerapps-docs/developer/data-platform/appendix-add-license-information-to-your-solution.md
Labels: assigned-to-contributors

#2582 pac pcf init runs npm install
  powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md
Labels: assigned-to-contributors

#2580 Update execute.md
  powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/online/execute.md
Labels: assigned-to-contributors

#2566 Fixing typo
  powerapps-docs/user/import-data.md
Labels: assigned-to-contributors

#2591 Update execute-multiple-requests.md
  powerapps-docs/developer/data-platform/org-service/execute-multiple-requests.md
Labels: assigned-to-contributors

#2585 Added Resources Type (resources.md) link
  powerapps-docs/developer/component-framework/reference/context.md
Labels: assigned-to-contributors

#2587 pac pcf init runs npm install (2)
  powerapps-docs/developer/component-framework/tutorial-create-model-driven-field-component.md
Labels: assigned-to-contributors
