Repository MicrosoftDocs/powerapps-docs, pull requests merged in 2021-08, with the labels that each got.

#2597 pac pcf init runs npm install (3)
  powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md
  powerapps-docs/developer/component-framework/debugging-custom-controls.md
Labels: assigned-to-contributors

#2469 Update lookupobjects.md
  powerapps-docs/developer/component-framework/reference/utility/lookupobjects.md
Labels: waiting-on-internal-feedback

#2594 Update test-studio-classic-pipeline-editor.md
  powerapps-docs/maker/canvas-apps/test-studio-classic-pipeline-editor.md
Labels: assigned-to-contributors

#2601 work-with-reports.md: fix link "Add reporting features to your model-driven app"
  powerapps-docs/user/work-with-reports.md
Labels: assigned-to-contributors

#2583 Update Sorting Note
  powerapps-docs/developer/component-framework/reference/dataset.md
Labels: waiting-on-internal-feedback, assigned-to-contributors

#2659 Update create-auto-number-attributes.md
  powerapps-docs/developer/data-platform/create-auto-number-attributes.md
Labels: assigned-to-contributors

#2657 Fixing some broken URLs
  powerapps-docs/maker/developer-plan.md
  powerapps-docs/maker/model-driven-apps/commanding-use-powerfx.md
  powerapps-docs/maker/model-driven-apps/design-productive-forms.md
  powerapps-docs/maker/model-driven-apps/page-canvas-components.md
  powerapps-docs/mobile/relevance-search-mobile.md
  powerapps-docs/mobile/run-powerapps-on-mobile.md
  powerapps-docs/sample-apps/crisis-financial-impact-tracker/configure-dashboards.md
  powerapps-docs/sample-apps/crisis-financial-impact-tracker/use-mobile-app.md
  powerapps-docs/sample-apps/emergency-response/configure-data-reporting.md
  powerapps-docs/sample-apps/emergency-response/overview.md
  powerapps-docs/sample-apps/emergency-response/use.md
  powerapps-docs/sample-apps/regional-emergency-response/upgrade.md
  powerapps-docs/teams/overview-of-the-power-apps-app.md
  powerapps-docs/user/navigation.md
Labels: assigned-to-contributors

#2680 Update authenticate-office365-deprecation.md
  powerapps-docs/developer/data-platform/authenticate-office365-deprecation.md
Labels: assigned-to-contributors
