Repository MicrosoftDocs/powerapps-docs, pull requests merged in 2021-06, with the labels that each got.

#2387 Create geospatial-map-excel.md
  powerapps-docs/maker/canvas-apps/geospatial-map-excel.md
Labels: assigned-to-contributors

#2386 Update geospatial-map-excel.md
  powerapps-docs/maker/canvas-apps/geospatial-map-excel.md
Labels: assigned-to-contributors

#2370 Update geospatial-map-excel.md
  powerapps-docs/maker/canvas-apps/geospatial-map-excel.md
Labels: assigned-to-contributors

#2369 Update geospatial-component-input-address.md
  powerapps-docs/maker/canvas-apps/geospatial-component-input-address.md
Labels: assigned-to-contributors

#2372 Update mixed-reality-add-pins-3d-model.md
  powerapps-docs/maker/canvas-apps/mixed-reality-add-pins-3d-model.md
Labels: assigned-to-contributors

#2416 Changed tables to rows where appropriate
  powerapps-docs/developer/data-platform/webapi/query-data-web-api.md
Labels: assigned-to-contributors

#2215 Update custom-api.md
  powerapps-docs/developer/data-platform/custom-api.md
Labels: assigned-to-contributors

#2225 Fixed copy/paste error
  powerapps-docs/developer/data-platform/custom-api.md
Labels: assigned-to-contributors

#2232 Update create-entity-web-api.md
  powerapps-docs/developer/data-platform/webapi/create-entity-web-api.md
Labels: assigned-to-contributors

#2366 Update gridrowdata.md
  powerapps-docs/developer/model-driven-apps/clientapi/reference/grids/gridrowdata.md
Labels: assigned-to-contributors, needs-writer-review

#2367 Update gridentity.md
  powerapps-docs/developer/model-driven-apps/clientapi/reference/grids/gridentity.md
Labels: assigned-to-contributors, needs-writer-review

#2441 Update solutioncomponent.md
  powerapps-docs/developer/data-platform/reference/entities/solutioncomponent.md
Labels: assigned-to-contributors

#2407 Update plug-ins.md
  powerapps-docs/developer/data-platform/plug-ins.md
Labels: assigned-to-contributors

#2355 Typo fix: Changing "Limits on number of tables -> entities returned"
  powerapps-docs/developer/data-platform/webapi/query-data-web-api.md
Labels: assigned-to-contributors

#2450 Edits for portals overview, term changes, and chatbot
  powerapps-docs/maker/portals/add-chatbot.md
  powerapps-docs/maker/portals/overview.md
  powerapps-docs/maker/portals/terminology-changes.md
Labels: assigned-to-contributors, do-not-merge

#2211 Expand query hint description
  powerapps-docs/developer/data-platform/org-service/use-queryexpression-class.md
Labels: assigned-to-contributors, waiting-on-internal-feedback

#2467 Updated some text on code component builder community resource
  powerapps-docs/developer/component-framework/community-resources.md
  powerapps-docs/developer/component-framework/media/pcf-builder-vscode.png
  powerapps-docs/developer/component-framework/media/pcf-builder-xrmtoolbox.png
Labels: assigned-to-contributors, needs-writer-review

#2474 Fixed some of the grammar and formatting with the tool section
  powerapps-docs/developer/component-framework/community-resources.md
Labels: assigned-to-contributors

#2452 Update create-edit-virtual-entities.md
  powerapps-docs/maker/data-platform/create-edit-virtual-entities.md
Labels: assigned-to-contributors

#2205 Update add-powerbi-dashboards.md
  powerapps-docs/user/add-powerbi-dashboards.md
Labels: assigned-to-contributors

#2489 Update performance-insights-categories.md
  powerapps-docs/maker/common/performance-insights-categories.md
Labels: assigned-to-contributors

#2497 Fix code typo
  powerapps-docs/maker/canvas-apps/geospatial-component-map.md
Labels: assigned-to-contributors

#2492 Changed LaunchTarget.Self to LaunchTarget.Replace
  powerapps-docs/maker/canvas-apps/functions/function-param.md
Labels: assigned-to-contributors

#2495 Update dominant plug-ins description
  powerapps-docs/maker/common/performance-insights-categories.md
Labels: assigned-to-contributors

#2192 Updated reference links in article
  powerapps-docs/maker/data-platform/EnvironmentVariables.md
Labels: assigned-to-contributors
