Repository MicrosoftDocs/powerapps-docs, pull requests merged in 2022-01, with the labels that each got.

#2950 Updates in "Update existing code components" note
  powerapps-docs/developer/component-framework/component-framework-for-canvas-apps.md
Labels: assigned-to-contributors

#2951 Update inspection.md
  powerapps-docs/teams/inspection.md
Labels: assigned-to-contributors

#2926 Update docfx.json
  powerapps-docs/docfx.json
Labels: do-not-merge

#2602 Updates prtFolder To Extract Name
  powerapps-docs/developer/data-platform/download-tools-nuget.md
Labels: assigned-to-contributors

#2961 Clearly Define When Alternate Key Values are Copied
  powerapps-docs/developer/data-platform/use-upsert-insert-update-record.md
Labels: assigned-to-contributors

#2962 Update EnvironmentVariables.md Make it clear action is required
  powerapps-docs/maker/data-platform/EnvironmentVariables.md
Labels: assigned-to-contributors

#2903 Update tutorial-buildapp-retrieve-videos.md
  powerapps-docs/teams/tutorial-buildapp-retrieve-videos.md
Labels: do-not-merge, assigned-to-contributors

#2973 Not a preview anymore
  powerapps-docs/maker/model-driven-apps/page-code-components.md
Labels: assigned-to-contributors

#3013 Removed a Note bullet and updated link to product name
  powerapps-docs/user/add-powerbi-dashboards.md
Labels: assigned-to-contributors

#2986 devtools-install: add link direct link to marketplace
  powerapps-docs/developer/data-platform/tools/devtools-install.md
Labels: assigned-to-contributors
