Repository MicrosoftDocs/powerapps-docs, pull requests merged in 2023-06, with the labels that each got.

#4143 Update use-fetchxml-construct-query.md
  powerapps-docs/developer/data-platform/use-fetchxml-construct-query.md
Labels: do-not-merge, assigned-to-contributors

#4426 Update object-output.md
  powerapps-docs/developer/component-framework/sample-controls/object-output.md
Labels: assigned-to-contributors

#4414 Update create-solution.md
  powerapps-docs/maker/data-platform/create-solution.md
Labels: assigned-to-contributors

#4408 Update create-app-side-panes.md
  powerapps-docs/developer/model-driven-apps/clientapi/create-app-side-panes.md
Labels: assigned-to-contributors

#4505 Editing request 14643
  powerapps-docs/maker/common/request-licenses-for-users.md
Labels: do-not-merge, needs-writer-review, copy edit complete
