Repository MicrosoftDocs/powerapps-docs, pull requests merged in 2023-03, with the labels that each got.

#4027 Fixed link
  powerapps-docs/maker/data-platform/work-with-any-data.md
Labels: assigned-to-contributors

#4096 Line 168 : Grammatical Error
  powerapps-docs/developer/data-platform/register-plug-in.md
Labels: assigned-to-contributors

#4094 Update dataverse-sql-query.md
  powerapps-docs/developer/data-platform/dataverse-sql-query.md
Labels: assigned-to-contributors

#4082 removed the currently in preview release
  powerapps-docs/developer/data-platform/authenticate-dot-net-framework.md
Labels: assigned-to-contributors

#3996 Type fixed
  powerapps-docs/mobile/power-apps-mobile-canvas-app-restarts.md
Labels: assigned-to-contributors

#3026 Update known-issues-limitations.md
  powerapps-docs/teams/known-issues-limitations.md
Labels: do-not-merge, assigned-to-contributors

#4156 Spelling of Select
  powerapps-docs/maker/canvas-apps/intro-maker-portal.md
Labels: assigned-to-contributors

#4167 Update Action Options and made other amendments.
  powerapps-docs/developer/data-platform/auditing/retrieve-audit-data.md
Labels: assigned-to-contributors

#4175 Minor Typos
  powerapps-docs/maker/canvas-apps/intro-maker-portal.md
Labels: assigned-to-contributors

#4174 Update set-up-timeline-control.md to include Cascading behavior
  powerapps-docs/maker/model-driven-apps/set-up-timeline-control.md
Labels: assigned-to-contributors

#4223 update timeline-attachment info
  powerapps-docs/user/add-activities.md
Labels: needs-writer-review

#4226 Fix spelling: buutton
  powerapps-docs/maker/model-driven-apps/commanding-use-powerfx.md
Labels: assigned-to-contributors

#4230 Update collaboration.md
  powerapps-docs/user/collaboration.md
Labels: assigned-to-contributors

#4232 Update getActiveProcess.md
  powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/activeprocess/getActiveProcess.md
Labels: assigned-to-contributors
