Repository MicrosoftDocs/powerapps-docs, pull requests merged in 2025-05, with the labels that each got.

#5422 Update the-power-apps-grid-control.md
  powerapps-docs/maker/model-driven-apps/the-power-apps-grid-control.md
Labels: assigned-to-contributors

#5398 Update create-app-barcode-scanner.md
  powerapps-docs/maker/canvas-apps/how-to/create-app-barcode-scanner.md
Labels: assigned-to-contributors

#5380 Update add-manage-connections.md
  powerapps-docs/maker/canvas-apps/add-manage-connections.md
Labels: assigned-to-contributors

#5345 Added AutoHeight property to HTML text control description
  powerapps-docs/maker/canvas-apps/controls/control-html-text.md
Labels: waiting-on-internal-feedback, assigned-to-contributors

#5194 Added Filtering limitations to ComboBox control
  powerapps-docs/teams/use-the-fluent-ui-controls.md
Labels: assigned-to-contributors

#4674 Clarified maximum on NumberOfSeries property
  powerapps-docs/maker/canvas-apps/controls/control-column-line-chart.md
Labels: waiting-on-internal-feedback, assigned-to-contributors, controls

#3728 Selected property of Combo Box Control
  powerapps-docs/maker/canvas-apps/controls/control-combo-box.md
Labels: waiting-on-internal-feedback, assigned-to-contributors, controls

#3483 ContentLanguage property added to button control
  powerapps-docs/maker/canvas-apps/controls/control-button.md
Labels: waiting-on-internal-feedback, assigned-to-contributors, controls
